connections:
  postgres:
    protocol: postgres
    username: docker
    password: postgres
    hostname: localhost
    port: 5432
    database: example
  local: file:local.db
  easycoast:
    protocol: postgres
    username: postgres
    password: teste01@
    hostname: localhost
    port: 5432
    database: easy_coast
init: |
  \echo 'welcome \033[1;34mscalet\033[0m, master of all data'
  \set SYNTAX_HL_STYLE catppuccin-mocha
  \set PROMPT1 '\033[1;35m%S%N%M%>%/ \033[3;1;32m%R%#\033[0m '
