add_newline = false
format = """$character"""
right_format = """
$sudo
$cmd_duration
$battery
$nix_shell
$git_branch
$git_status
$package
$nodejs
$bun
$deno
$java
$gradle
$php
$python
$dotnet
$rust
$golang
$kotlin
$haskell
$c
$lua
"""

[character]
error_symbol = "[➜](red bold)"
success_symbol = "[➜](green bold)"
vimcmd_symbol = "[➜](blue bold)"
vimcmd_replace_one_symbol = "[➜](purple bold)"
vimcmd_replace_symbol = "[➜](purple bold)"
vimcmd_visual_symbol = "[➜](yellow bold)"

[directory]
format = "[$path$read_only]($style)"
read_only_style = "cyan"
truncation_length = 100
truncate_to_repo = false
read_only = "  "

[nix_shell]
format = '[$symbol$state (\($name\))]($style) '
disabled = false
symbol = " "
style = "bold dimmed blue"

[shell]
disabled = false
style = "black bold"
format = "[ $indicator ]($style)"
fish_indicator = "󰻴"
bash_indicator = ""
nu_indicator = ""
zsh_indicator = ""
cmd_indicator = ""
powershell_indicator = ""

[package]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed yellow"
symbol = "󰏗"

[nodejs]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed green"
symbol = ""

[bun]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed red"
symbol = ""

[deno]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed cyan"
symbol = ""

[java]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed red"
symbol = ""

[php]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[python]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[dotnet]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed purple"
symbol = ""

[rust]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed red"
symbol = ""

[golang]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed cyan"
symbol = ""

[kotlin]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[haskell]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed purple"
symbol = ""

[c]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed purple"
symbol = ""

[lua]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = "󰢱"

[gradle]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed cyan"
symbol = ""

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bold dimmed purple"
symbol = ""

[git_status]
style = "bold dimmed italic purple"

[time]
disabled = false
style = "black bold"
format = "[ $time ]($style)"

[cmd_duration]
disabled = false
style = "black bold"
format = "[ took $duration ]($style)"

[battery]
display = [{ style = "black bold", threshold = 80 }]
format = "[ $symbol$percentage ]($style)"

[sudo]
disabled = false
style = "bold red dimmed"
format = "[$symbol]($style)"
symbol = "  "
